# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 837ef91ba9ab7dc892aef4e336d516d82095be3294daac6df2e341e8df4e698bf2e0c87b08ccb80a5878eec314a237bb7624dcdb0bf8c7b9e8d7c6fea4df69e1

test:
  secret_key_base: 5efa2717377c7e8a55b643b89c727d29aa04b8ed5367288a86e671277ece719b37c91e312911189cfa90d51475c42d57924008b1db59b92cc3300cd9d719cd50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
